Update mangio fork to latest (#1)
* Correction of Japanese nuances (#577)

* Correction of Japanese nuances

* Add new line

* Fix OpenBLAS warning (#583)

Fixes the error msg: "OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata"

* Add new defaults for infer-web.py & adjust english translation (#584)

* Adjust defaults of index and volume scale

* Adjust eng translation for index and volume envelope

* Fix links (#596)

* fix extract locale

* Format code (#612)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* 🎨 同步 locale (#613)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Bump gradio from 3.14.0 to 3.34.0 (#614)

Bumps [gradio](https://github.com/gradio-app/gradio) from 3.14.0 to 3.34.0.
- [Release notes](https://github.com/gradio-app/gradio/releases)
- [Changelog](https://github.com/gradio-app/gradio/blob/main/CHANGELOG.md)
- [Commits](https://github.com/gradio-app/gradio/compare/v3.14.0...v3.34.0)

---
updated-dependencies:
- dependency-name: gradio
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* move changelogs to docs folder

* 优化 config.py

* 优化代码结构

* add dlmodels.sh

* Fix the index out of bounds bug in extract_feature_print.py (#560)

Check if the length of sys.argv is 6, instead of 5, to cover sys.argv[5]. Otherwise when the length is 6, it runs the else body and tries to access sys.argv[6] in line 13, which is an error.

* Update LICENSE

* fix extract feature in MPS device

* 优化代码结构

* Update README.md

* Format code (#624)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* update index training script v2 (#643)

* update index training script v2

* Apply Code Formatter Change

---------

Co-authored-by: gak123 <gak123@users.noreply.github.com>

* Fix realtime gui under linux (#609)

* Fix init problem about devices index outbound

* Fix file browse file type

* Fix sd stream channels problem, fix it to 2

---------

Co-authored-by: 源文雨 <41315874+fumiama@users.noreply.github.com>

* Format code (#644)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* fix boolean parsing (#629)

* Update README.md (#646)

* added tr support (#653)

* Changes by create-pull-request action (#655)

* 🎨 同步 locale

* Update tr_TR.json

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: 源文雨 <41315874+fumiama@users.noreply.github.com>

* added ru support ru-RU.json (#661)

* added ru support ru-RU.json

Russian translation by redoverflow

* updated description for extract

* Added italian translation json (#676)

* 🎨 同步 locale (#699)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* add torchcrepe to pyproject (#696)

* Add directML support to RVC for AMD & Intel GPU supported (#707)

* Use sys.executable to determine --pycmd (#715)

* Use sys.executable to determine --pycmd

In some systems, `python` may not correctly refer to the virtual environment's `python` used for webui, or it even refers to Python 2.

Also in Windows, when the webui is run directly through `venv\Scripts\python` without activating the virtual environment, the system python will be picked instead of the one inside virtual environment.

* Remove reduntant "or".

* Format code (#716)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* add rmvpe support

add rmvpe support

* 最先进人声音高提取算法RMVPE已支持，效果默秒全！

最先进人声音高提取算法RMVPE已支持，效果默秒全！

* Update and rename gui.py to gui_v0.py

* Add files via upload

* Add files via upload

* 实时GUI支持rmvpe

实时GUI支持rmvpe

* Update rvc_for_realtime.py

* Update LICENSE

* Create MIT协议暨相关引用库协议

* Format code (#727)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* fix: gen-locale

* 🎨 同步 locale (#743)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Add .sh run script for macOS & linux, fix error on macs with low vram. (#737)

* Add .sh run script

* Update extract_feature_print.py

* Remove `requirements_macOS.txt`

* Fix dependency error (#745)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lightning 2.0.2 requires fastapi<0.89.0,>=0.69.0, but you have fastapi 0.100.0 which is incompatible.
so-vits-svc-fork 3.14.1 requires fastapi==0.88, but you have fastapi 0.100.0 which is incompatible.

* fix mps in gui-v1.py (#769)

* Fix mps on realtime

* Added back repeat chs

* Fix dependency conflict in last pull request (#775)

The conflict is caused by:
    The user requested starlette>=0.25.0
    fastapi 0.88.0 depends on starlette==0.22.0

fastapi 0.88.0 package will resolve dependency automatically, remove the starlette>=0.25.0 will fix the conflict.

* Format code (#779)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* Attempt at fixing import for infer pack

* basic rmvpe support, no training yet

You need the weight file from huggingface to use this. Rmvpe seems faster and higher quality than mangio-crepe

* Gradio req. updated

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Ftps <63702646+Tps-F@users.noreply.github.com>
Co-authored-by: Justin John <34035011+justinjohn0306@users.noreply.github.com>
Co-authored-by: 源文雨 <41315874+fumiama@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: sungchura <sungchura@gmail.com>
Co-authored-by: Rice Cake <gak141808@gmail.com>
Co-authored-by: gak123 <gak123@users.noreply.github.com>
Co-authored-by: Yurzi <43744366+Yurzi@users.noreply.github.com>
Co-authored-by: tocky <55511257+tttocklll@users.noreply.github.com>
Co-authored-by: Ozan Ayrıkan <42660635+Hasqer@users.noreply.github.com>
Co-authored-by: Devyatyi9 <devyatyi9@gmail.com>
Co-authored-by: Valerio Montieri <74709553+sw4rm3r@users.noreply.github.com>
Co-authored-by: Roberts Slisans <roberts.slisans@gmail.com>
Co-authored-by: Zhang, Di <pamzerbhu@live.com>
Co-authored-by: Miku AuahDark <auahdark687291@gmail.com>
Co-authored-by: RVC-Boss <129054828+RVC-Boss@users.noreply.github.com>
Co-authored-by: Naozumi <naozumi0512@gmail.com>
Co-authored-by: 丸子 <princeb4d@gmail.com>